### ISSUE TITLE
[SUGGESTION] Make a song on building

### ISSUE THREAD

**Issue by SkyCraft78** [BakaAless/InventoryAPI#12]
Hi!
Why not adding a specific song on the GUI creation, and this one will be played when we open the GUI ?
Example:
```java
        InventoryAPI inventory = InventoryAPI.create(INSTANCE);
        inventory
                .setSize(54)
                // Here we add the song:
                .setSong(Sound.AMBIENT_BASALT_DELTAS_ADDITIONS)
                .setRefresh(true);
```
I know we can do it ourself, but it could be pretty good to improve organization.
Regards,
Sky

**Comment by BakaAless** [comment]
Hi, thank's for your pull request. As you said, you can do it by yourself. There is no interest in this function. In fact, it's more of a sound than a song.

Aless
